version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            python setup.py build_ext --inplace
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
      - run: python -m flake8 --ignore W3,E3,E5,E74 rankfm/
      - run: python -m pytest -r Efp tests/

